<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XTI_App.Abstractions" Version="1.8.48" />
    <PackageReference Include="XTI_Core" Version="1.10.25" />
    <PackageReference Include="XTI_Forms" Version="1.8.48" />
  </ItemGroup>

</Project>
